version: '3'

volumes:
    providence_web:
    providence_db:
    pawtucket_web:

services:
    providence_db:
        image: mariadb
        restart: always
        networks:
            collectiveaccess:
                ipv4_address: 172.16.0.2
        volumes:
            - providence_db:/var/lib/mysql
        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
            - MYSQL_DATABASE=providence
            - MYSQL_USER=providence
            - MYSQL_PASSWORD=prvdnc

    providence_web:
        image: iametza/collective-access:1.7.8
        restart: always
        networks:
            collectiveaccess:
                ipv4_address: 172.16.0.3
        ports:
            - 8080:80
        volumes:
            - providence_web:/var/www/html
        environment:
            - PROVIDENCE_DB_HOST=providence_db
            - PROVIDENCE_DB_USER=providence
            - PROVIDENCE_DB_PASSWORD=prvdnc
            - PROVIDENCE_DB_NAME=providence

    pawtucket_web:
        image: iametza/pawtucket:1.7.8
        restart: always
        networks:
            collectiveaccess:
                ipv4_address: 172.16.0.4
         ports:
            - 8081:80
        volumes:
            - pawtucket_web:/var/www/html/pawtucket
networks:
    collectiveaccess:
        driver: bridge
        ipam:
            config:
                - subnet: "172.16.0.0/16"
