version: '3'

volumes:
    collectiveaccess_web:
    collectiveaccess_db:
    
services:
    collectiveaccess_db:
        image: mariadb
        container_name: collectiveaccess_db
        restart: always
        networks:
            collectiveaccess:
                ipv4_address: 172.16.0.2
        volumes:
            - collectiveaccess_db:/var/lib/mysql
        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
            - MYSQL_DATABASE=providence
            - MYSQL_USER=providence
            - MYSQL_PASSWORD=prvdnc

    collectiveaccess_web:
        image: iametza/collective-access:1.7.8
        container_name: collectiveaccess_web
        restart: always
        networks:
            collectiveaccess:
                ipv4_address: 172.16.0.3
        ports:
            - 8080:80
        volumes:
            - collectiveaccess_web:/var/www/html
        environment:
            - PROVIDENCE_DB_HOST=providence_db
            - PROVIDENCE_DB_USER=providence
            - PROVIDENCE_DB_PASSWORD=prvdnc
            - PROVIDENCE_DB_NAME=providence
   
networks:
    collectiveaccess:
        driver: bridge
        ipam:
            config:
                - subnet: "172.16.0.0/16"
